name: test

on:
  push:
    branches:
      - "**"
      - "!main"
      - "!alpha"
      - "!beta"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install libudev pkg-config
        run: sudo apt-get update && sudo apt-get install -y libudev-dev pkg-config
      - name: test
        run: make ci
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}